In [44]:
import pandas as pd
import numpy as n
data=pd.read_csv("synthetic_dataset.csv")
data.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [3]:
data.tail()

     Category   Price    Rating         Stock  Discount
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

In [58]:
data.isnull().tail(20)

      Category  Price  Rating  Stock  Discount
4342     False  False   False  False     False
4343     False  False   False  False     False
4344      True   True    True   True     False
4345     False  False    True  False     False
4346     False  False    True   True     False
4347      True  False   False  False      True
4348      True  False   False   True     False
4349     False  False    True  False     False
4350      True  False   False  False     False
4351     False  False    True  False      True
4352      True  False   False  False     False
4353      True  False    True   True     False
4354      True  False   False  False      True
4355      True   True    True  False     False
4356      True   True    True  False     False
4357      True  False   False   True     False
4358     False  False    True  False     False
4359      True  False    True  False     False
4360     False  False   False   True     False
4361      True   True   False   True     False

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4362 entries, 0 to 4361
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  1614 non-null   object
 1   Price     4188 non-null   float64
 2   Rating    2312 non-null   float64
 3   Stock     3010 non-null   object
 4   Discount  3970 non-null   float64
dtypes: float64(3), object(2)
memory usage: 136.4+ KB

In [7]:
data.dropna()

     Category   Price    Rating         Stock  Discount
6           C   667.0  3.668341      In Stock      41.0
7           A  7125.0  4.983998  Out of Stock       7.0
8           A  2777.0  2.678384      In Stock       6.0
11          A  3772.0  4.890750      In Stock      45.0
15          A  7936.0  3.032832      In Stock      44.0
...       ...     ...       ...           ...       ...
4313        A  4167.0  2.432036  Out of Stock      22.0
4320        C  7630.0  3.475273      In Stock       0.0
4333        D  2424.0  4.716295      In Stock      49.0
4342        D  9847.0  3.667649  Out of Stock      49.0
4343        B   843.0  2.752754  Out of Stock      48.0

[540 rows x 5 columns]

In [54]:
data["Category"].replace(' ',n.nan)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
4357    NaN
4358      B
4359    NaN
4360      D
4361    NaN
Name: Category, Length: 4362, dtype: object

In [55]:
data['Stock'].fillna('In Stock')

0           In Stock
1           In Stock
2           In Stock
3           In Stock
4       Out of Stock
            ...
4357        In Stock
4358    Out of Stock
4359    Out of Stock
4360        In Stock
4361        In Stock
Name: Stock, Length: 4362, dtype: object

In [64]:
data['Discount'].fillna(data['Discount'].mean())

0        0.0
1       38.0
2        0.0
3       33.0
4       23.0
        ...
4357    49.0
4358     4.0
4359     9.0
4360    40.0
4361     0.0
Name: Discount, Length: 4362, dtype: float64

In [66]:
data['Rating'].fillna(data['Rating']).mode()

0       1.000366
1       1.003103
2       1.003437
3       1.004563
4       1.005715
          ...
2307    4.991690
2308    4.992002
2309    4.992309
2310    4.992992
2311    4.997818
Name: Rating, Length: 2312, dtype: float64

In [73]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Stock.com"]=le.fit_transform(data["Stock"])
print(data["Stock"],data["Stock.com"])

0       2
1       2
2       0
3       2
4       1
       ..
4357    2
4358    1
4359    1
4360    2
4361    2
Name: Stock, Length: 4362, dtype: int32 0       2
1       2
2       0
3       2
4       1
       ..
4357    2
4358    1
4359    1
4360    2
4361    2
Name: Stock.com, Length: 4362, dtype: int32